### PR TITLE
TacGenericConverter Fix and move FINAL to zSDHISMS MM pass

### PR DESCRIPTION
**Pull request by RedAV8R**

### CODE REVIEW

**Comment by sumghai** [comment]
I'm familiar with the `:FOR` keyword, but I don't quite understand why you've used `:FOR[zSDHISMS]`, since it doesn't match any folder or assembly names associated with SDHI SMS. Could you please elaborate?

Also:

- The umbilical patch must be applied at all times.

- The TAC-LS patch for SDHI SMS must override whatever defaults TAC-LS originally provides, since the patch increases the command pod's solid life support resources and storage (food, waste) to eight days without a corresponding increase in "fluid" (liquid/gas) life support resources and storage  (oxygen, water, CO2, wastewater), and adds the required additional fluid resources to the Service Module itself.

I'd rather your proposed changes don't affect my original intentions for this mod, so if you could elaborate on these as well, that would be appreciated.

**Comment by Kerbas-ad-astra** [comment]
Patches tagged FOR[X] (or BEFORE[X] or AFTER[X]) run in alphabetical order of "X", so marking these patches as "FOR[zSDHISMS]" will cause them to run almost at the very end of MM's patching, but before patches tagged FINAL (which I understand is best-practice, so that FINAL can be left for end-users).  RedAV8R could just as well have used zFOO or zAnything as zSDHISMS, as the Z is what's important, but he probably chose zSDHISMS because it's meaningful and unlikely to inadvertently collide with any other mod's name.

If they were tagged NEEDS[zSDHISMS] (or BEFORE or AFTER), then the patches would not run, because (as you say) there is no zSDHISMS folder or DLL, but FOR[X] signals to Module Manager that "X" is present, so they'll work.

**Comment by RedAV8R** [comment]
Exactly as Kerbas-ad-astra has commented. :FOR doesn't have to be associated with anything. You can make anything be :FOR[WhateverYouWant] and that's the pass it will run on. If it doesn't already exist via folder or assembly then it will create it.

One thing I'd like to add is that now that :FOR[zSDHISMS] has been defined. Something else can be :BEFORE or :AFTER or :NEEDS.

I hope this clarifies what I did.
As such. 1) The umbilical will be run. and 2) The TACLS patch will be run as well.

In fact, everything is as it was done before just simply moved up a slight notch.

WAS: TAC-LS, SDHI, FINAL
NOW: TAC-LS, SDHI, zSDHISMS, FINAL.

Now instead of running on the FINAL pass and requiring anything that may want to modify that, like RO, to have the physical file after your patches, simply requires that a :FOR pass be alphabetically after zSDHISMS (like :FOR[zz***]) OR can run on the FINAL pass.

**Comment by sumghai** [comment]
Thanks for the clarifications @RedAV8R and @Kerbas-ad-astra - PR accepted with thanks!

**Pull request merged**
